### PR TITLE
docs: Add Kotlin examples to README

### LINKED ISSUE #1: Examples of configuring using Gradle Kotlin DSL would be helpful

### PR DESCRIPTION
**Pull request by jakemarsden**
Closes #1

### CODE REVIEW

**Comment by jakemarsden** [comment]
@dalewking This seems to work for me but I'm unfamiliar with Kotlin so any feedback is appreciated, e.g. if it can be simplified. The full package name seems a bit ugly.

**Comment by themichailov** [comment]
gitHooks {
    setHooks(mapOf("pre-commit" to "check"))
}

**Comment by ghost** [comment]
Yes. We can omit package. I am using like this:

```gradle
gitHooks {
    setHooks(mapOf("pre-commit" to "check"))
}
```

**Comment by jakemarsden** [comment]
@themichailov Thanks

**Pull request merged**
